// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1GMhXWJbr9sEuxKnJw8XGPBgf_--qhM0',
    appId: '1:827330610431:web:ef0009ce40c5b1b7f5f8ca',
    messagingSenderId: '827330610431',
    projectId: 'chat-app-476c3',
    authDomain: 'chat-app-476c3.firebaseapp.com',
    storageBucket: 'chat-app-476c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQJ_uytmSpcJVH63Fc0A67xxH8BruP0ho',
    appId: '1:827330610431:android:df0afa58d6f7789af5f8ca',
    messagingSenderId: '827330610431',
    projectId: 'chat-app-476c3',
    storageBucket: 'chat-app-476c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN6mxW5UL0Uz52ysQjTbvE4BCS5ua5BGA',
    appId: '1:827330610431:ios:a49f2058126f3d22f5f8ca',
    messagingSenderId: '827330610431',
    projectId: 'chat-app-476c3',
    storageBucket: 'chat-app-476c3.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN6mxW5UL0Uz52ysQjTbvE4BCS5ua5BGA',
    appId: '1:827330610431:ios:a8316dad6e5b0b67f5f8ca',
    messagingSenderId: '827330610431',
    projectId: 'chat-app-476c3',
    storageBucket: 'chat-app-476c3.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
